# Generated by Django 3.0.7 on 2021-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobilenum',
            field=models.IntegerField(),
        ),
    ]
